name: Module Tidy Check

on:
  - pull_request

jobs:
  tidy:
    name: go mod tidy
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Check go mod tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
            echo "go.mod or go.sum is not tidy"
            git diff go.mod go.sum
            echo "Please run: go mod tidy"
            exit 1
          fi
